version: '3'
services:
  mongodb:
    container_name: mongomongodb
    image: mongo
    ports:
    - 27017:27017

  postgresdb:
    container_name: postgrespostgresdb
    image: postgres
    ports:
    - 5555:5432
    environment:
    - POSTGRES_USER='postgres'
    - POSTGRES_PASSWORD='postgres'
    - POSTGRES_DB='tweet_collector'

  tweet_collector:
    container_name: tweet_scrape
    build: tweet_collector
    volumes:
    - ./tweet_collector/:/code
    depends_on:
    - mongodb

  etl:
    container_name: tweet_etl
    build: etl
    volumes:
    - ./etl/:/code
    depends_on:
    - mongodb
    - postgresdb
